on: [push, pull_request]

name: Continuous Integration

jobs:
  check:
    name: Rust Cargo Check
    runs-on: ubuntu-latest
    steps:
      - name: Install apt packages
        run: sudo apt-get install -yy libudev-dev
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: "1.49.0"
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check

  test:
    name: Rust Cargo Test
    runs-on: ubuntu-latest
    steps:
      - name: Install apt packages
        run: sudo apt-get install -yy libudev-dev
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: "1.49.0"
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test

  fmt:
    name: Rust Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: "1.49.0"
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Rust Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Install apt packages
        run: sudo apt-get install -yy libudev-dev
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: "1.49.0"
          override: true
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  tarpaulin:
    name: Rust Tarpaulin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: "1.49.0"
          override: true

      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.16.0'
          args: '--run-types AllTargets -- --test-threads 1'
          out-type: 'Html'

      - name: Archive code coverage results
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: tarpaulin-report.html
